In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
import tensorflow

In [6]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
model = Sequential()

In [8]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\avani\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.get_weights()

[array([[ 1.0991398 ,  1.0353886 ],
        [-1.103532  , -0.19738138]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.18663907],
        [-0.67260164]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
np.array([0.,0.],dtype=np.float32),
np.array([[0.1],[0.1]],dtype=np.float32),
np.array([0.],dtype=np.float32)]

In [22]:
new_weights[1].shape

(2,)

In [23]:
model.set_weights(new_weights)

In [24]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [26]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)

In [27]:
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [30]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=74,verbose=1,batch_size=1)

Epoch 1/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.2295 
Epoch 2/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1693 
Epoch 3/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0622 
Epoch 4/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5009 
Epoch 5/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0286 
Epoch 6/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0750     
Epoch 7/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.7260     
Epoch 8/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0264 
Epoch 9/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0062 
Epoch 10/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8555 
Epoch 11/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.3906 
Epoch 12/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5874 
Epoch 13/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5481 
Epoch 14/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8522 
Epoch 15/74
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0655 
Epoch 16/74
4/4 ━━━━━━━━━━

In [31]:
model.get_weights()

[array([[0.36213154, 0.36213154],
        [0.4101729 , 0.4101729 ]], dtype=float32),
 array([0.2938159, 0.2938159], dtype=float32),
 array([[0.39827362],
        [0.39827362]], dtype=float32),
 array([0.21693563], dtype=float32)]